In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('D:\SummerResearch\data\credit\creditcard.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [8]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [11]:
df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

# chech original onehot data

In [19]:
df_ori_train = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_train.csv')
df_ori_test = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_test.csv')

print("train data")
print(df_ori_train['Class'].value_counts())

print("\ntest data")
print(df_ori_test['Class'].value_counts())

train data
Class
0    274332
1       475
Name: count, dtype: int64

test data
Class
0    9983
1      17
Name: count, dtype: int64

## check synthetic data

### ctgan

In [9]:
import pandas as pd
df_ctgan = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_sdv_100k.csv')

df_ctgan['Class'].value_counts()

Class
0    67012
1    32988
Name: count, dtype: int64

### rf & xgb

In [21]:
df_rf = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_sdv_rf_100k.csv')
df_rf['Class'].value_counts()

Class
0    100000
Name: count, dtype: int64

In [22]:
df_xgb = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_sdv_xgb_100k.csv')
df_xgb['Class'].value_counts()

Class
0    100000
Name: count, dtype: int64

In [29]:
df_rf_new = pd.read_csv('D:\SummerResearch\data\credit\\new\onehot_credit_sdv_rf_100k.csv')
df_rf_new['Class'].value_counts()

Class
0    100000
Name: count, dtype: int64

In [30]:
df_xgb_new = pd.read_csv('D:\SummerResearch\data\credit\\new\onehot_credit_sdv_xgb_100k.csv')
df_xgb_new['Class'].value_counts()

Class
0    100000
Name: count, dtype: int64

### categorical & gaussian

In [ ]:
df_cat = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_sdv_categorical_100k.csv')
df_cat['Class'].value_counts()

Class
0    100000
Name: count, dtype: int64

In [5]:
df_gauss = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_sdv_gaussian_100k.csv')
df_gauss['Class'].value_counts()

Class
0    99865
1      135
Name: count, dtype: int64

# fit categoricalNB to onehot_train

In [15]:
import pandas as pd
import sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, f1_score




def create_label_categoricalNB(xtrain, ytrain, xtest, target_name, filename=None, alpha=1.0, force_alpha=True):
  """
  alpha and force_alpha are parameters for Laplace smoothing (sklearn default is alpha=1.0 and force_alpha=True)
  for no smoothing, set alpha=0 and force_alpha=False
  """

#   x_null = xtrain.isnull().sum()
#   print("\n\nNull values in xtrain: ", x_null)

#   x_null = xtest.isnull().sum()
#   print("\n\nNull values in xtest: ", x_null)

  # xtrain and ytrain are one hot encoded
  # normalize data to [0,1] because CategoricalNB only accepts non negative values
  scaler = MinMaxScaler()
  xtrain = xtrain.reindex(sorted(xtrain.columns), axis=1)
  xtest = xtest.reindex(sorted(xtest.columns), axis=1)

  xtrain_scaled = scaler.fit_transform(xtrain)
  xtest_scaled = scaler.transform(xtest)

  # xtrain = xtrain.reindex(sorted(xtrain.columns), axis=1)
  # xtest = xtest.reindex(sorted(xtest.columns), axis=1)
  xtrain_scaled = pd.DataFrame(xtrain_scaled, columns = xtrain.columns)
  xtest_scaled = pd.DataFrame(xtest_scaled, columns = xtest.columns)
  # xtrain_scaled = xtrain_scaled.reindex(sorted(xtrain_scaled.columns), axis=1)
  # xtest_scaled = xtest_scaled.reindex(sorted(xtest_scaled.columns), axis=1)

  cnb = CategoricalNB(alpha=alpha, force_alpha=force_alpha).fit(xtrain_scaled, ytrain)
  ytest = cnb.predict(xtest_scaled)

  ytest_df = pd.DataFrame(ytest, columns = [target_name])
  test = pd.concat([xtest, ytest_df], axis=1)


  pred_train = cnb.predict(xtrain_scaled)
  pred_test = cnb.predict(xtest_scaled)
  print("Train Accuracy: ", accuracy_score(ytrain, pred_train))
  print("Train F1: ", f1_score(ytrain, pred_train))

  if filename:
    test.to_csv(filename)
  return test

In [17]:
import sklearn
import sklearn.naive_bayes

df_ori_train = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_train.csv')
df_ori_test = pd.read_csv('D:\SummerResearch\data\credit\onehot_credit_test.csv')


create_label_categoricalNB(df_ori_train.drop(columns=['Class']), df_ori_train['Class'], df_ori_test.drop(columns=['Class']), 'Class', filename=None)

Train Accuracy:  0.9982751531074536
Train F1:  0.0125

,Amount,Time,V1,V10,V11,V12,V13,V14,V15,V16,...,V27,V28,V3,V4,V5,V6,V7,V8,V9,Class
0,80.44,44989.0,-1.371736,-0.608030,-1.188074,0.470557,0.143783,-0.124659,-0.431355,-0.655387,...,0.277520,0.048077,1.626688,1.364716,-0.526173,-0.244988,-0.096144,0.577885,0.076863,0
1,2.69,79526.0,1.220008,-0.026235,0.024615,-0.191337,-1.162973,0.547083,1.144940,0.212466,...,-0.037581,0.021605,0.706575,0.760421,-0.864820,-1.330687,-0.019438,-0.161322,0.218103,0
2,1.49,73003.0,1.275739,0.101748,-0.687432,-0.801273,-1.917309,0.944715,0.891869,-0.127481,...,-0.020418,0.006836,-0.152200,1.126124,-0.134749,-1.240019,0.422188,-0.247006,0.010903,0
3,2.12,107703.0,-0.574110,-1.393796,0.419036,-1.873573,2.854949,1.229656,0.487578,-0.305573,...,0.095518,0.078741,2.266583,-0.101942,0.082950,-0.259461,0.415946,-0.099760,1.187640,0
4,1.00,87750.0,-2.872232,-0.053102,-1.854918,0.322148,0.120693,0.650434,-0.422105,0.739238,...,0.472424,0.342083,-1.519114,-2.942693,-0.039393,-0.955091,0.116400,1.236276,0.759272,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,19.35,33346.0,1.123529,0.051692,0.797970,0.890229,-0.570118,0.327485,-0.723610,-0.410057,...,0.030853,0.003551,0.268037,1.212620,0.023332,0.326939,-0.055368,0.173710,0.115082,0
9996,42.40,65148.0,0.173076,0.188728,-0.626567,0.338652,1.369869,0.062537,1.404494,-0.427687,...,0.138851,0.236363,0.668506,0.905634,-0.004652,-0.364979,0.729545,-0.281115,-0.597436,0
9997,11.50,161267.0,2.035926,0.041533,-1.845218,-0.484249,-0.846778,-0.082341,0.524432,0.587690,...,-0.027727,-0.056377,-0.532987,0.342721,-0.609694,-0.204698,-0.741449,0.050581,1.487033,0
9998,132.71,41214.0,1.029897,-0.489418,-1.652273,-0.040322,-0.506437,-0.448091,-0.155484,0.170497,...,-0.062446,0.026017,0.640365,0.162302,-0.975068,0.115195,-0.548418,0.110838,1.346927,0
9999,10.00,143192.0,-0.229296,-0.553779,0.515981,0.843988,0.444545,0.089025,-0.898759,0.327422,...,-0.081220,-0.043186,0.714033,-0.823979,0.678652,-0.545063,0.584168,-0.015142,-0.355663,0

## fit rf and xgb on original onehot

In [25]:
# import sklearn.ensemble
# from sklearn.ensemble import RandomForestClassifier
# import sklearn.metrics
# from sklearn.metrics import accuracy_score, f1_score

# model_rf = RandomForestClassifier()
# model_rf.fit(df_ori_train.drop(columns=['Class']), df_ori_train['Class'])
pred_rf_test = model_rf.predict(df_ori_test.drop(columns=['Class']))
pred_rf_train = model_rf.predict(df_ori_train.drop(columns=['Class']))



print("RF Train Accuracy: ", accuracy_score(df_ori_train['Class'], pred_rf_train))
print("RF Train F1: ", f1_score(df_ori_train['Class'], pred_rf_train))
print("")
print("RF Test Accuracy: ", accuracy_score(df_ori_test['Class'], pred_rf_test))
print("RF Test F1: ", f1_score(df_ori_test['Class'], pred_rf_test))

RF Train Accuracy:  1.0
RF Train F1:  1.0

RF Test Accuracy:  0.9996
RF Test F1:  0.875

In [27]:
import xgboost as xgb
from xgboost import XGBClassifier
import sklearn.metrics
from sklearn.metrics import accuracy_score, f1_score
model_xgb = XGBClassifier()
model_xgb.fit(df_ori_train.drop(columns=['Class']), df_ori_train['Class'])
pred_xgb_test = model_xgb.predict(df_ori_test.drop(columns=['Class']))
pred_xgb_train = model_xgb.predict(df_ori_train.drop(columns=['Class']))

print("XGB Train Accuracy: ", accuracy_score(df_ori_train['Class'], pred_xgb_train))
print("XGB Train F1: ", f1_score(df_ori_train['Class'], pred_xgb_train))
print("")
print("XGB Test Accuracy: ", accuracy_score(df_ori_test['Class'], pred_xgb_test))
print("XGB Test F1: ", f1_score(df_ori_test['Class'], pred_xgb_test))

XGB Train Accuracy:  1.0
XGB Train F1:  1.0

XGB Test Accuracy:  0.9997
XGB Test F1:  0.9032258064516129